[workspace]
authors = ["Maulik Madhavi <maulik.madhavi@gmail.com>"]
channels = ["conda-forge"]
name = "video_annotation"
platforms = ["win-64","linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
pip = ">=25.3,<26"
ffmpeg = ">=8.0.1,<9"
pylint = ">=4.0.4,<5"

[pypi-dependencies]
flask = ">=3.0.0,<4"
pandas = ">=3.0.0, <4"
